backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

collections:
  - name: 'projects'
    label: 'Projects'
    folder: 'src/content/projects'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Thumbnail image', name: 'image', widget: 'string' }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          default: false,
        }
      - { label: 'Description', name: 'description', widget: 'string' }
